"""verification schema

Revision ID: 0f03c3a33e7c
Revises: e87cf0b333f2
Create Date: 2026-07-10 13:26:13.906060

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0f03c3a33e7c"
down_revision: str | Sequence[str] | None = "e87cf0b333f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session_end_verifications",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("baseline_id", sa.Integer(), nullable=False),
        sa.Column("verified_by", sa.Integer(), nullable=False),
        sa.Column("verified_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["baseline_id"],
            ["room_inventory_baselines.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verified_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("baseline_id"),
    )
    op.create_table(
        "verification_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("verification_id", sa.Integer(), nullable=False),
        sa.Column("baseline_item_id", sa.Integer(), nullable=False),
        sa.Column("current_quantity", sa.Integer(), nullable=False),
        sa.Column(
            "current_condition",
            sa.Enum("good", "fair", "damaged", "missing", name="verificationcondition"),
            nullable=False,
        ),
        sa.Column(
            "flag",
            sa.Enum("ok", "missing", "damaged", "quantity_mismatch", name="verificationflag"),
            server_default="ok",
            nullable=False,
        ),
        sa.Column("notes", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["baseline_item_id"],
            ["baseline_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verification_id"],
            ["session_end_verifications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("verification_id", "baseline_item_id"),
    )
    op.create_index(
        op.f("ix_verification_items_baseline_item_id"),
        "verification_items",
        ["baseline_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_items_verification_id"),
        "verification_items",
        ["verification_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Drop tables directly rather than dropping indexes first (autogenerate's
    # default) — MySQL refuses to drop an index still backing a foreign key.
    op.drop_table("verification_items")
    op.drop_table("session_end_verifications")
