"""identity and access schema

Revision ID: 169ee503d9e7
Revises:
Create Date: 2026-07-10 13:02:43.647260

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "169ee503d9e7"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "halls",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "hall_type",
            sa.Enum("regular", "tetfund_danjuma", "hall_6", "hall_7", name="halltype"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("full_name", sa.String(length=150), nullable=False),
        sa.Column("email", sa.String(length=150), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.Enum("admin", "porter", "student", name="userrole"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "rooms",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("hall_id", sa.Integer(), nullable=False),
        sa.Column("room_number", sa.String(length=20), nullable=False),
        sa.Column("corner_label", sa.String(length=10), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["hall_id"],
            ["halls.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hall_id", "room_number", "corner_label"),
    )
    op.create_index(op.f("ix_rooms_hall_id"), "rooms", ["hall_id"], unique=False)
    op.create_table(
        "porter_room_assignments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("porter_id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["porter_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("porter_id", "room_id"),
    )
    op.create_index(
        op.f("ix_porter_room_assignments_porter_id"),
        "porter_room_assignments",
        ["porter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_porter_room_assignments_room_id"),
        "porter_room_assignments",
        ["room_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Drop tables directly (rather than dropping indexes first, autogenerate's
    # default) — MySQL refuses to drop an index still backing a foreign key
    # constraint; dropping the table removes its indexes and FKs together.
    op.drop_table("porter_room_assignments")
    op.drop_table("rooms")
    op.drop_table("users")
    op.drop_table("halls")
    # ### end Alembic commands ###
