"""asset reference schema

Revision ID: 17d0a8d0883c
Revises: 169ee503d9e7
Create Date: 2026-07-10 13:11:37.257121

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "17d0a8d0883c"
down_revision: str | Sequence[str] | None = "169ee503d9e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("display_name", sa.String(length=50), nullable=False),
        sa.Column(
            "sign_off_group", sa.Enum("corner", "shared", name="signoffgroup"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "hall_asset_rules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "hall_type",
            sa.Enum("regular", "tetfund_danjuma", "hall_6", "hall_7", name="halltype"),
            nullable=False,
        ),
        sa.Column("asset_type_id", sa.Integer(), nullable=False),
        sa.Column("default_quantity", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_type_id"],
            ["asset_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hall_type", "asset_type_id"),
    )
    op.create_index(
        op.f("ix_hall_asset_rules_asset_type_id"),
        "hall_asset_rules",
        ["asset_type_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Drop tables directly rather than dropping indexes first (autogenerate's
    # default) — MySQL refuses to drop an index still backing a foreign key.
    op.drop_table("hall_asset_rules")
    op.drop_table("asset_types")
