"""condition report schema

Revision ID: 243f2faefb75
Revises: 0f03c3a33e7c
Create Date: 2026-07-10 13:28:25.699131

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "243f2faefb75"
down_revision: str | Sequence[str] | None = "0f03c3a33e7c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "condition_reports",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("allocation_id", sa.Integer(), nullable=False),
        sa.Column("asset_type_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("reported_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("open", "acknowledged", name="conditionreportstatus"),
            server_default="open",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["allocation_id"],
            ["student_room_allocations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["asset_type_id"],
            ["asset_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_condition_reports_allocation_id"),
        "condition_reports",
        ["allocation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Drop the table directly rather than dropping its index first (autogenerate's
    # default) — MySQL refuses to drop an index still backing a foreign key.
    op.drop_table("condition_reports")
