"""session and allocation schema

Revision ID: 653cd21f94f0
Revises: 17d0a8d0883c
Create Date: 2026-07-10 13:20:01.380090

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "653cd21f94f0"
down_revision: str | Sequence[str] | None = "17d0a8d0883c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "closed", name="sessionstatus"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "student_room_allocations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("allocated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "vacated", name="allocationstatus"),
            server_default="active",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("student_id", "session_id"),
    )
    op.create_index(
        op.f("ix_student_room_allocations_room_id"),
        "student_room_allocations",
        ["room_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_room_allocations_session_id"),
        "student_room_allocations",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_room_allocations_student_id"),
        "student_room_allocations",
        ["student_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Drop tables directly rather than dropping indexes first (autogenerate's
    # default) — MySQL refuses to drop an index still backing a foreign key.
    op.drop_table("student_room_allocations")
    op.drop_table("sessions")
