"""baseline and sign-off schema

Revision ID: e87cf0b333f2
Revises: 653cd21f94f0
Create Date: 2026-07-10 13:23:06.259630

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e87cf0b333f2"
down_revision: str | Sequence[str] | None = "653cd21f94f0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "room_inventory_baselines",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("locked", sa.Boolean(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("room_id", "session_id"),
    )
    op.create_index(
        op.f("ix_room_inventory_baselines_room_id"),
        "room_inventory_baselines",
        ["room_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_room_inventory_baselines_session_id"),
        "room_inventory_baselines",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "baseline_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("baseline_id", sa.Integer(), nullable=False),
        sa.Column("asset_type_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "condition",
            sa.Enum("good", "fair", "damaged", name="assetcondition"),
            server_default="good",
            nullable=False,
        ),
        sa.Column("notes", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_type_id"],
            ["asset_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["baseline_id"],
            ["room_inventory_baselines.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("baseline_id", "asset_type_id"),
    )
    op.create_index(
        op.f("ix_baseline_items_baseline_id"), "baseline_items", ["baseline_id"], unique=False
    )
    op.create_table(
        "sign_offs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("baseline_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column(
            "sign_off_group", sa.Enum("corner", "shared", name="signoffgroup"), nullable=False
        ),
        sa.Column(
            "status", sa.Enum("confirmed", "contested", name="signoffstatus"), nullable=False
        ),
        sa.Column("comment", sa.String(length=500), nullable=True),
        sa.Column("signed_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["baseline_id"],
            ["room_inventory_baselines.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("baseline_id", "student_id", "sign_off_group"),
    )
    op.create_index(op.f("ix_sign_offs_baseline_id"), "sign_offs", ["baseline_id"], unique=False)
    op.create_index(op.f("ix_sign_offs_student_id"), "sign_offs", ["student_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Drop tables directly rather than dropping indexes first (autogenerate's
    # default) — MySQL refuses to drop an index still backing a foreign key.
    op.drop_table("sign_offs")
    op.drop_table("baseline_items")
    op.drop_table("room_inventory_baselines")
